#!/usr/bin/env bash
#
# Update grub config to use new kernel. You need to be root to run this script.

# After installing the new kernel for the first time, `/boot/grub2/grub.cfg` is
# added a new menuentry with the new kernel as target, BUT weirdly its id is
# the same as the id of the old menuentry. So we run `grub2-mkconfig` again to
# generate a different menuentry id.
generated_grub_file="/boot/grub2/grub.cfg"
grub2-mkconfig -o "$generated_grub_file"

set -eo pipefail

add_setting() {
  local name="$1"
  local value="$2"
  local grub_file="/etc/default/grub"
  if grep "$name=" "$grub_file" &>/dev/null; then
    sed -i.bak "s/^$name=.*\$/$name=$value/" "$grub_file"
  else
    echo -e "\n$name=$value" >> "$grub_file"
  fi
}

add_setting GRUB_TIMEOUT 5

menuentry_id=$(grep '^menuentry' "$generated_grub_file" | head -1 | sed "s/^.*\\$menuentry_id_option \\+'\\(.*\\)'.*/\\1/")

add_setting GRUB_DEFAULT "$menuentry_id"

grub2-mkconfig -o "$generated_grub_file"
